import Navbar from '@/components/Navbar/Navbar'
import AllSection from '@/components/Section/AllSalleSection';
import Link from 'next/link';
import React from 'react';

const AllGym = ["ACCROBRANCHE", "ACROSPORT", "AEROBIC", "AEROBIC SPORTIVE", "AERODANCE", "AIKIDO", "ALPINISME", "AQUA GYM", "ARTS MARTIAUX", "ARTS MARTIAUX ARTISTIQUES", "ATHLÉTISME", "AUTOCROSS", "AVIATION", "AVIRON", "BABY FOOT", "BADMINTON", "BASKETBALL", "BILLARD", "BODYBOARD", "BOWLING", "BOXE", "BOXE AMÉRICAINE", "BOXE ANGLAISE", "BOXE FRANÇAISE", "BOXE THAÏLANDAISE", "BRIDGE", "CANOË KAYAK", "CAPOEIRA", "CHASSE", "CIRQUE", "COMBAT", "COURSE", "CROSS-TRAINING", "CROSSE", "CROSSFIT", "CYCLISME", "CYCLO-CROSS", "DANSE", "DANSE AFRICAINE", "DANSE CLASSIQUE", "DANSE CONTEMPORAINE", "DANSE INDIENNE", "DANSE JAZZ", "DANSE MODERN JAZZ", "DANSE ORIENTALE", "DANSES CARAÏBES", "DANSES LATINES", "DESCENTE EN RAPPEL", "ECHECS", "ÉQUITATION", "ESCALADE", "ESCRIME", "FITNESS", "FLYBOARD", "FOOT À 5", "FOOT À 7", "FOOTBALL", "FOOTGOLF", "FULL-CONTACT", "GLISSE", "GOLF", "GRAPPLING", "GYMNASTIQUE", "HALTÉROPHILIE", "HANDBALL", "HAPKIDO", "HIP HOP", "HOCKEY", "IAÏDO", "JEET KUNE DO", "JET SKI", "JIU-JITSU BRÉSILIEN", "JU-JITSU", "JUDO", "K1", "KARATÉ", "KARTING", "KAYAK", "KAYAK SURF", "KEMPO", "KICK BOXING", "KITE SURF", "KITESURF", "KUNG FU", "LUTTE", "MMA", "MOTO", "MUAY THAÏ", "MUSCULATION", "NATATION", "NAUTISME", "PADDLE", "PADEL", "PAINTBALL", "PARACHUTISME", "PARAPENTE", "PÊCHE", "PÊCHE SOUS-MARINE", "PÊCHE SPORTIVE", "PENCHAK SILAT", "PÉTANQUE", "PILATES", "PING-PONG", "PLANCHE À VOILE", "PLONGÉE", "PLONGÉE SOUS-MARINE", "POLO", "QI GONG", "QUAD", "RAFTING", "RAGGA", "RAID", "RAID NATURE", "RALLYE AUTOMOBILE", "RANDONNÉE", "RANDONNÉE ÉQUESTRE", "RANDONNÉE PÉDESTRE", "RAQUETTE À NEIGE", "ROLLER", "RUGBY", "SALSA", "SAMBO", "SELF DÉFENSE", "SKATEBOARD", "SKI", "SKI ALPIN", "SKI DE RANDONNÉE", "SKI NAUTIQUE", "SPORT BOULE", "SPORTS ÉQUESTRES", "SQUASH", "SURF", "TAE BO", "TAEKWONDO", "TAI CHI", "TAÏ CHI CHUAN", "TAÏ JITSU", "TAIHOJUTSU", "TANGO", "TENNIS", "TENNIS DE TABLE", "THAING BANDO", "TIR", "TIR À L'ARC", "TREKKING", "ULTIMATE FRISBEE", "VAN LANG VO DAO", "VOILE", "VOLLEY BALL", "VOLLEY-BALL", "VTT", "WAKEBOARD", "WING CHUN", "WUSHU", "YOGA", "ZUMBA"]
{/* <Link href={`/salles/${e}`}>{e}</Link> */ }

const AllSallesPage = () => {
    return (
        <div>
            <Navbar />
            <div>
                <AllSection />
            </div>
            <div>
                {AllGym.map((e, idx) => (
                    <Link href={`/salles/${e}`}>{e}</Link>
                ))}
            </div>
        </div>
    )
}

export default AllSallesPage;
